// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.AddressBook in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

public class AddressBook(
  people: List<Person> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<AddressBook, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Person#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val people: List<Person> = immutableCopyOf("people", people)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AddressBook) return false
    if (unknownFields != other.unknownFields) return false
    if (people != other.people) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + people.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (people.isNotEmpty()) result += """people=$people"""
    return result.joinToString(prefix = "AddressBook{", separator = ", ", postfix = "}")
  }

  public fun copy(people: List<Person> = this.people, unknownFields: ByteString =
      this.unknownFields): AddressBook = AddressBook(people, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AddressBook> = object : ProtoAdapter<AddressBook>(
      FieldEncoding.LENGTH_DELIMITED, 
      AddressBook::class, 
      "type.googleapis.com/com.yunlong.particle.proto.AddressBook", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: AddressBook): Int {
        var size = value.unknownFields.size
        size += Person.ADAPTER.asRepeated().encodedSizeWithTag(1, value.people)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: AddressBook): Unit {
        Person.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.people)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: AddressBook): Unit {
        writer.writeBytes(value.unknownFields)
        Person.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.people)
      }

      public override fun decode(reader: ProtoReader): AddressBook {
        val people = mutableListOf<Person>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> people.add(Person.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return AddressBook(
          people = people,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: AddressBook): AddressBook = value.copy(
        people = value.people.redactElements(Person.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<AddressBook> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
