// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.Alignment in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class Alignment(
  public override val `value`: Int,
) : WireEnum {
  TOP_ALIGNMENT(0),
  CENTER_ALIGNMENT(1),
  BOTTOM_ALIGNMENT(2),
  START_ALIGNMENT(3),
  END_ALIGNMENT(4),
  TOP_START(5),
  TOP_CENTER(6),
  TOP_END(7),
  BOTTOM_START(8),
  BOTTOM_CENTER(9),
  BOTTOM_END(10),
  CENTER_START(11),
  CENTER_END(12),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Alignment> = object : EnumAdapter<Alignment>(
      Alignment::class, 
      PROTO_3, 
      Alignment.TOP_ALIGNMENT
    ) {
      public override fun fromValue(`value`: Int): Alignment? = Alignment.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Alignment? = when (value) {
      0 -> TOP_ALIGNMENT
      1 -> CENTER_ALIGNMENT
      2 -> BOTTOM_ALIGNMENT
      3 -> START_ALIGNMENT
      4 -> END_ALIGNMENT
      5 -> TOP_START
      6 -> TOP_CENTER
      7 -> TOP_END
      8 -> BOTTOM_START
      9 -> BOTTOM_CENTER
      10 -> BOTTOM_END
      11 -> CENTER_START
      12 -> CENTER_END
      else -> null
    }
  }
}
