// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.Arrangement in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class Arrangement(
  public override val `value`: Int,
) : WireEnum {
  START(0),
  END(1),
  TOP(2),
  BOTTOM(3),
  CENTER(4),
  SPACE_EVENLY(5),
  SPACE_BETWEEN(6),
  SPACE_AROUND(7),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Arrangement> = object : EnumAdapter<Arrangement>(
      Arrangement::class, 
      PROTO_3, 
      Arrangement.START
    ) {
      public override fun fromValue(`value`: Int): Arrangement? = Arrangement.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Arrangement? = when (value) {
      0 -> START
      1 -> END
      2 -> TOP
      3 -> BOTTOM
      4 -> CENTER
      5 -> SPACE_EVENLY
      6 -> SPACE_BETWEEN
      7 -> SPACE_AROUND
      else -> null
    }
  }
}
