// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.BottomBarComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * BottomBar view layout component.
 */
public class BottomBarComponent(
  elements: List<Particle> = emptyList(),
  /**
   * The currently selected item id in the NavigationView
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val selectedElement: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<BottomBarComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Child elements in the component.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val elements: List<Particle> = immutableCopyOf("elements", elements)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BottomBarComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (elements != other.elements) return false
    if (selectedElement != other.selectedElement) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + elements.hashCode()
      result = result * 37 + selectedElement.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (elements.isNotEmpty()) result += """elements=$elements"""
    result += """selectedElement=${sanitize(selectedElement)}"""
    return result.joinToString(prefix = "BottomBarComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    elements: List<Particle> = this.elements,
    selectedElement: String = this.selectedElement,
    unknownFields: ByteString = this.unknownFields,
  ): BottomBarComponent = BottomBarComponent(elements, selectedElement, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BottomBarComponent> = object :
        ProtoAdapter<BottomBarComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      BottomBarComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.BottomBarComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: BottomBarComponent): Int {
        var size = value.unknownFields.size
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.elements)
        if (value.selectedElement != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.selectedElement)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: BottomBarComponent): Unit {
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
        if (value.selectedElement != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.selectedElement)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: BottomBarComponent): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.selectedElement != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.selectedElement)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
      }

      public override fun decode(reader: ProtoReader): BottomBarComponent {
        val elements = mutableListOf<Particle>()
        var selectedElement: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> elements.add(Particle.ADAPTER.decode(reader))
            2 -> selectedElement = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BottomBarComponent(
          elements = elements,
          selectedElement = selectedElement,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: BottomBarComponent): BottomBarComponent = value.copy(
        elements = value.elements.redactElements(Particle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<BottomBarComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
