// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.BoxComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Z-axis stack layout component.
 */
public class BoxComponent(
  elements: List<Particle> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<BoxComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Child elements in the component.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val elements: List<Particle> = immutableCopyOf("elements", elements)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BoxComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (elements != other.elements) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + elements.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (elements.isNotEmpty()) result += """elements=$elements"""
    return result.joinToString(prefix = "BoxComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(elements: List<Particle> = this.elements, unknownFields: ByteString =
      this.unknownFields): BoxComponent = BoxComponent(elements, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BoxComponent> = object : ProtoAdapter<BoxComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      BoxComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.BoxComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: BoxComponent): Int {
        var size = value.unknownFields.size
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.elements)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: BoxComponent): Unit {
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: BoxComponent): Unit {
        writer.writeBytes(value.unknownFields)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
      }

      public override fun decode(reader: ProtoReader): BoxComponent {
        val elements = mutableListOf<Particle>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> elements.add(Particle.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return BoxComponent(
          elements = elements,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: BoxComponent): BoxComponent = value.copy(
        elements = value.elements.redactElements(Particle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<BoxComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
