// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ButtonComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Button Element used to create a clickable button
 */
public class ButtonComponent(
  /**
   * Element(s) displayed on the button
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val elements: Particle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ButtonComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ButtonComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (elements != other.elements) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (elements?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (elements != null) result += """elements=$elements"""
    return result.joinToString(prefix = "ButtonComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(elements: Particle? = this.elements, unknownFields: ByteString =
      this.unknownFields): ButtonComponent = ButtonComponent(elements, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ButtonComponent> = object : ProtoAdapter<ButtonComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ButtonComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ButtonComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ButtonComponent): Int {
        var size = value.unknownFields.size
        if (value.elements != null) size += Particle.ADAPTER.encodedSizeWithTag(1, value.elements)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ButtonComponent): Unit {
        if (value.elements != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.elements)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ButtonComponent): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.elements != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.elements)
      }

      public override fun decode(reader: ProtoReader): ButtonComponent {
        var elements: Particle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> elements = Particle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ButtonComponent(
          elements = elements,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ButtonComponent): ButtonComponent = value.copy(
        elements = value.elements?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ButtonComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
