// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.CheckBoxComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * CheckBox Element used to create a checkbox
 */
public class CheckBoxComponent(
  /**
   * The label displayed next to the checkbox
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
  )
  public val label: String? = null,
  /**
   * The initial state of the checkbox
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
  )
  public val isChecked: Boolean? = null,
  /**
   * The color of the checkbox when it is not selected.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.yunlong.particle.proto.ColorModifier#ADAPTER",
  )
  public val uncheckedColor: ColorModifier? = null,
  /**
   * The color of the checkbox when it is selected.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.yunlong.particle.proto.ColorModifier#ADAPTER",
  )
  public val checkedColor: ColorModifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<CheckBoxComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CheckBoxComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (label != other.label) return false
    if (isChecked != other.isChecked) return false
    if (uncheckedColor != other.uncheckedColor) return false
    if (checkedColor != other.checkedColor) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (isChecked?.hashCode() ?: 0)
      result = result * 37 + (uncheckedColor?.hashCode() ?: 0)
      result = result * 37 + (checkedColor?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (label != null) result += """label=${sanitize(label)}"""
    if (isChecked != null) result += """isChecked=$isChecked"""
    if (uncheckedColor != null) result += """uncheckedColor=$uncheckedColor"""
    if (checkedColor != null) result += """checkedColor=$checkedColor"""
    return result.joinToString(prefix = "CheckBoxComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    label: String? = this.label,
    isChecked: Boolean? = this.isChecked,
    uncheckedColor: ColorModifier? = this.uncheckedColor,
    checkedColor: ColorModifier? = this.checkedColor,
    unknownFields: ByteString = this.unknownFields,
  ): CheckBoxComponent = CheckBoxComponent(label, isChecked, uncheckedColor, checkedColor,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CheckBoxComponent> = object : ProtoAdapter<CheckBoxComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      CheckBoxComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.CheckBoxComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: CheckBoxComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.label)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.isChecked)
        size += ColorModifier.ADAPTER.encodedSizeWithTag(3, value.uncheckedColor)
        size += ColorModifier.ADAPTER.encodedSizeWithTag(4, value.checkedColor)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: CheckBoxComponent): Unit {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
        ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.isChecked)
        ColorModifier.ADAPTER.encodeWithTag(writer, 3, value.uncheckedColor)
        ColorModifier.ADAPTER.encodeWithTag(writer, 4, value.checkedColor)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: CheckBoxComponent): Unit {
        writer.writeBytes(value.unknownFields)
        ColorModifier.ADAPTER.encodeWithTag(writer, 4, value.checkedColor)
        ColorModifier.ADAPTER.encodeWithTag(writer, 3, value.uncheckedColor)
        ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.isChecked)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.label)
      }

      public override fun decode(reader: ProtoReader): CheckBoxComponent {
        var label: String? = null
        var isChecked: Boolean? = null
        var uncheckedColor: ColorModifier? = null
        var checkedColor: ColorModifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> label = ProtoAdapter.STRING.decode(reader)
            2 -> isChecked = ProtoAdapter.BOOL.decode(reader)
            3 -> uncheckedColor = ColorModifier.ADAPTER.decode(reader)
            4 -> checkedColor = ColorModifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CheckBoxComponent(
          label = label,
          isChecked = isChecked,
          uncheckedColor = uncheckedColor,
          checkedColor = checkedColor,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: CheckBoxComponent): CheckBoxComponent = value.copy(
        uncheckedColor = value.uncheckedColor?.let(ColorModifier.ADAPTER::redact),
        checkedColor = value.checkedColor?.let(ColorModifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<CheckBoxComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
