// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ColorValue in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ColorValue(
  /**
   * The red component of the color, from 0-255.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val red: Int = 0,
  /**
   * The green component of the color, from 0-255.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val green: Int = 0,
  /**
   * The blue component of the color, from 0-255.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val blue: Int = 0,
  /**
   * The alpha component of the color, from 0-255.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val alpha: Float = 0f,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ColorValue, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ColorValue) return false
    if (unknownFields != other.unknownFields) return false
    if (red != other.red) return false
    if (green != other.green) return false
    if (blue != other.blue) return false
    if (alpha != other.alpha) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + red.hashCode()
      result = result * 37 + green.hashCode()
      result = result * 37 + blue.hashCode()
      result = result * 37 + alpha.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """red=$red"""
    result += """green=$green"""
    result += """blue=$blue"""
    result += """alpha=$alpha"""
    return result.joinToString(prefix = "ColorValue{", separator = ", ", postfix = "}")
  }

  public fun copy(
    red: Int = this.red,
    green: Int = this.green,
    blue: Int = this.blue,
    alpha: Float = this.alpha,
    unknownFields: ByteString = this.unknownFields,
  ): ColorValue = ColorValue(red, green, blue, alpha, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ColorValue> = object : ProtoAdapter<ColorValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      ColorValue::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ColorValue", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ColorValue): Int {
        var size = value.unknownFields.size
        if (value.red != 0) size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.red)
        if (value.green != 0) size += ProtoAdapter.UINT32.encodedSizeWithTag(2, value.green)
        if (value.blue != 0) size += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.blue)
        if (!value.alpha.equals(0f)) size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.alpha)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ColorValue): Unit {
        if (value.red != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.red)
        if (value.green != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.green)
        if (value.blue != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.blue)
        if (!value.alpha.equals(0f)) ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.alpha)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ColorValue): Unit {
        writer.writeBytes(value.unknownFields)
        if (!value.alpha.equals(0f)) ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.alpha)
        if (value.blue != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.blue)
        if (value.green != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.green)
        if (value.red != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.red)
      }

      public override fun decode(reader: ProtoReader): ColorValue {
        var red: Int = 0
        var green: Int = 0
        var blue: Int = 0
        var alpha: Float = 0f
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> red = ProtoAdapter.UINT32.decode(reader)
            2 -> green = ProtoAdapter.UINT32.decode(reader)
            3 -> blue = ProtoAdapter.UINT32.decode(reader)
            4 -> alpha = ProtoAdapter.FLOAT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ColorValue(
          red = red,
          green = green,
          blue = blue,
          alpha = alpha,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ColorValue): ColorValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ColorValue> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
