// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ConditionType in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ConditionType(
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ConditionType, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ConditionType) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  public override fun hashCode(): Int = unknownFields.hashCode()

  public override fun toString(): String = "ConditionType{}"

  public fun copy(unknownFields: ByteString = this.unknownFields): ConditionType =
      ConditionType(unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ConditionType> = object : ProtoAdapter<ConditionType>(
      FieldEncoding.LENGTH_DELIMITED, 
      ConditionType::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ConditionType", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ConditionType): Int {
        var size = value.unknownFields.size
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ConditionType): Unit {
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ConditionType): Unit {
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): ConditionType {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return ConditionType(
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ConditionType): ConditionType = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ConditionType> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
