// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.Destination in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class Destination(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val route: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val content: Particle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<Destination, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Destination) return false
    if (unknownFields != other.unknownFields) return false
    if (route != other.route) return false
    if (content != other.content) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + route.hashCode()
      result = result * 37 + (content?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """route=${sanitize(route)}"""
    if (content != null) result += """content=$content"""
    return result.joinToString(prefix = "Destination{", separator = ", ", postfix = "}")
  }

  public fun copy(
    route: String = this.route,
    content: Particle? = this.content,
    unknownFields: ByteString = this.unknownFields,
  ): Destination = Destination(route, content, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Destination> = object : ProtoAdapter<Destination>(
      FieldEncoding.LENGTH_DELIMITED, 
      Destination::class, 
      "type.googleapis.com/com.yunlong.particle.proto.Destination", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: Destination): Int {
        var size = value.unknownFields.size
        if (value.route != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.route)
        if (value.content != null) size += Particle.ADAPTER.encodedSizeWithTag(2, value.content)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: Destination): Unit {
        if (value.route != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.route)
        if (value.content != null) Particle.ADAPTER.encodeWithTag(writer, 2, value.content)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: Destination): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.content != null) Particle.ADAPTER.encodeWithTag(writer, 2, value.content)
        if (value.route != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.route)
      }

      public override fun decode(reader: ProtoReader): Destination {
        var route: String = ""
        var content: Particle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> route = ProtoAdapter.STRING.decode(reader)
            2 -> content = Particle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Destination(
          route = route,
          content = content,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: Destination): Destination = value.copy(
        content = value.content?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<Destination> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
