// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ElementComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ElementComponent(
  /**
   * Used to create a clickable button
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.ButtonComponent#ADAPTER",
    oneofName = "element",
  )
  public val button: ButtonComponent? = null,
  /**
   * Used to display text
   */
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.TextComponent#ADAPTER",
    oneofName = "element",
  )
  public val label: TextComponent? = null,
  /**
   * Used to display an image
   */
  @field:WireField(
    tag = 3,
    adapter = "com.yunlong.particle.proto.ImageComponent#ADAPTER",
    oneofName = "element",
  )
  public val image: ImageComponent? = null,
  /**
   * Used to create a text input field
   */
  @field:WireField(
    tag = 4,
    adapter = "com.yunlong.particle.proto.TextFieldComponent#ADAPTER",
    oneofName = "element",
  )
  public val textField: TextFieldComponent? = null,
  /**
   * Used to create a multiline text input field
   */
  @field:WireField(
    tag = 5,
    adapter = "com.yunlong.particle.proto.TextEditorComponent#ADAPTER",
    oneofName = "element",
  )
  public val textEditor: TextEditorComponent? = null,
  /**
   * Used to create a slider
   */
  @field:WireField(
    tag = 6,
    adapter = "com.yunlong.particle.proto.SliderComponent#ADAPTER",
    oneofName = "element",
  )
  public val slider: SliderComponent? = null,
  /**
   * Used to create a switch toggle
   */
  @field:WireField(
    tag = 7,
    adapter = "com.yunlong.particle.proto.ToggleComponent#ADAPTER",
    oneofName = "element",
  )
  public val toggle: ToggleComponent? = null,
  /**
   * Used to create a checkbox
   */
  @field:WireField(
    tag = 8,
    adapter = "com.yunlong.particle.proto.CheckBoxComponent#ADAPTER",
    oneofName = "element",
  )
  public val checkbox: CheckBoxComponent? = null,
  /**
   * Used to create a radio button
   */
  @field:WireField(
    tag = 9,
    adapter = "com.yunlong.particle.proto.RadioButtonComponent#ADAPTER",
    oneofName = "element",
  )
  public val radioButton: RadioButtonComponent? = null,
  /**
   * Used to create a dropdown list
   */
  @field:WireField(
    tag = 10,
    adapter = "com.yunlong.particle.proto.PickerComponent#ADAPTER",
    oneofName = "element",
  )
  public val picker: PickerComponent? = null,
  /**
   * Used to create a toolbar
   */
  @field:WireField(
    tag = 11,
    adapter = "com.yunlong.particle.proto.TopAppBarComponent#ADAPTER",
    oneofName = "element",
  )
  public val topAppBar: TopAppBarComponent? = null,
  /**
   * Used to create a bottom bar
   */
  @field:WireField(
    tag = 12,
    adapter = "com.yunlong.particle.proto.BottomBarItemComponent#ADAPTER",
    oneofName = "element",
  )
  public val bottomBarItem: BottomBarItemComponent? = null,
  /**
   * Used to create an alert dialog
   */
  @field:WireField(
    tag = 13,
    adapter = "com.yunlong.particle.proto.AlertComponent#ADAPTER",
    oneofName = "element",
  )
  public val alert: AlertComponent? = null,
  /**
   * Used to create an action sheet
   */
  @field:WireField(
    tag = 14,
    adapter = "com.yunlong.particle.proto.ActionSheetComponent#ADAPTER",
    oneofName = "element",
  )
  public val actionSheet: ActionSheetComponent? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ElementComponent, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(button, label, image, textField, textEditor, slider, toggle, checkbox,
        radioButton, picker, topAppBar, bottomBarItem, alert, actionSheet) <= 1) {
      "At most one of button, label, image, textField, textEditor, slider, toggle, checkbox, radioButton, picker, topAppBar, bottomBarItem, alert, actionSheet may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ElementComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (button != other.button) return false
    if (label != other.label) return false
    if (image != other.image) return false
    if (textField != other.textField) return false
    if (textEditor != other.textEditor) return false
    if (slider != other.slider) return false
    if (toggle != other.toggle) return false
    if (checkbox != other.checkbox) return false
    if (radioButton != other.radioButton) return false
    if (picker != other.picker) return false
    if (topAppBar != other.topAppBar) return false
    if (bottomBarItem != other.bottomBarItem) return false
    if (alert != other.alert) return false
    if (actionSheet != other.actionSheet) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (button?.hashCode() ?: 0)
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (image?.hashCode() ?: 0)
      result = result * 37 + (textField?.hashCode() ?: 0)
      result = result * 37 + (textEditor?.hashCode() ?: 0)
      result = result * 37 + (slider?.hashCode() ?: 0)
      result = result * 37 + (toggle?.hashCode() ?: 0)
      result = result * 37 + (checkbox?.hashCode() ?: 0)
      result = result * 37 + (radioButton?.hashCode() ?: 0)
      result = result * 37 + (picker?.hashCode() ?: 0)
      result = result * 37 + (topAppBar?.hashCode() ?: 0)
      result = result * 37 + (bottomBarItem?.hashCode() ?: 0)
      result = result * 37 + (alert?.hashCode() ?: 0)
      result = result * 37 + (actionSheet?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (button != null) result += """button=$button"""
    if (label != null) result += """label=$label"""
    if (image != null) result += """image=$image"""
    if (textField != null) result += """textField=$textField"""
    if (textEditor != null) result += """textEditor=$textEditor"""
    if (slider != null) result += """slider=$slider"""
    if (toggle != null) result += """toggle=$toggle"""
    if (checkbox != null) result += """checkbox=$checkbox"""
    if (radioButton != null) result += """radioButton=$radioButton"""
    if (picker != null) result += """picker=$picker"""
    if (topAppBar != null) result += """topAppBar=$topAppBar"""
    if (bottomBarItem != null) result += """bottomBarItem=$bottomBarItem"""
    if (alert != null) result += """alert=$alert"""
    if (actionSheet != null) result += """actionSheet=$actionSheet"""
    return result.joinToString(prefix = "ElementComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    button: ButtonComponent? = this.button,
    label: TextComponent? = this.label,
    image: ImageComponent? = this.image,
    textField: TextFieldComponent? = this.textField,
    textEditor: TextEditorComponent? = this.textEditor,
    slider: SliderComponent? = this.slider,
    toggle: ToggleComponent? = this.toggle,
    checkbox: CheckBoxComponent? = this.checkbox,
    radioButton: RadioButtonComponent? = this.radioButton,
    picker: PickerComponent? = this.picker,
    topAppBar: TopAppBarComponent? = this.topAppBar,
    bottomBarItem: BottomBarItemComponent? = this.bottomBarItem,
    alert: AlertComponent? = this.alert,
    actionSheet: ActionSheetComponent? = this.actionSheet,
    unknownFields: ByteString = this.unknownFields,
  ): ElementComponent = ElementComponent(button, label, image, textField, textEditor, slider,
      toggle, checkbox, radioButton, picker, topAppBar, bottomBarItem, alert, actionSheet,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ElementComponent> = object : ProtoAdapter<ElementComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ElementComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ElementComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ElementComponent): Int {
        var size = value.unknownFields.size
        size += ButtonComponent.ADAPTER.encodedSizeWithTag(1, value.button)
        size += TextComponent.ADAPTER.encodedSizeWithTag(2, value.label)
        size += ImageComponent.ADAPTER.encodedSizeWithTag(3, value.image)
        size += TextFieldComponent.ADAPTER.encodedSizeWithTag(4, value.textField)
        size += TextEditorComponent.ADAPTER.encodedSizeWithTag(5, value.textEditor)
        size += SliderComponent.ADAPTER.encodedSizeWithTag(6, value.slider)
        size += ToggleComponent.ADAPTER.encodedSizeWithTag(7, value.toggle)
        size += CheckBoxComponent.ADAPTER.encodedSizeWithTag(8, value.checkbox)
        size += RadioButtonComponent.ADAPTER.encodedSizeWithTag(9, value.radioButton)
        size += PickerComponent.ADAPTER.encodedSizeWithTag(10, value.picker)
        size += TopAppBarComponent.ADAPTER.encodedSizeWithTag(11, value.topAppBar)
        size += BottomBarItemComponent.ADAPTER.encodedSizeWithTag(12, value.bottomBarItem)
        size += AlertComponent.ADAPTER.encodedSizeWithTag(13, value.alert)
        size += ActionSheetComponent.ADAPTER.encodedSizeWithTag(14, value.actionSheet)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ElementComponent): Unit {
        ButtonComponent.ADAPTER.encodeWithTag(writer, 1, value.button)
        TextComponent.ADAPTER.encodeWithTag(writer, 2, value.label)
        ImageComponent.ADAPTER.encodeWithTag(writer, 3, value.image)
        TextFieldComponent.ADAPTER.encodeWithTag(writer, 4, value.textField)
        TextEditorComponent.ADAPTER.encodeWithTag(writer, 5, value.textEditor)
        SliderComponent.ADAPTER.encodeWithTag(writer, 6, value.slider)
        ToggleComponent.ADAPTER.encodeWithTag(writer, 7, value.toggle)
        CheckBoxComponent.ADAPTER.encodeWithTag(writer, 8, value.checkbox)
        RadioButtonComponent.ADAPTER.encodeWithTag(writer, 9, value.radioButton)
        PickerComponent.ADAPTER.encodeWithTag(writer, 10, value.picker)
        TopAppBarComponent.ADAPTER.encodeWithTag(writer, 11, value.topAppBar)
        BottomBarItemComponent.ADAPTER.encodeWithTag(writer, 12, value.bottomBarItem)
        AlertComponent.ADAPTER.encodeWithTag(writer, 13, value.alert)
        ActionSheetComponent.ADAPTER.encodeWithTag(writer, 14, value.actionSheet)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ElementComponent): Unit {
        writer.writeBytes(value.unknownFields)
        ActionSheetComponent.ADAPTER.encodeWithTag(writer, 14, value.actionSheet)
        AlertComponent.ADAPTER.encodeWithTag(writer, 13, value.alert)
        BottomBarItemComponent.ADAPTER.encodeWithTag(writer, 12, value.bottomBarItem)
        TopAppBarComponent.ADAPTER.encodeWithTag(writer, 11, value.topAppBar)
        PickerComponent.ADAPTER.encodeWithTag(writer, 10, value.picker)
        RadioButtonComponent.ADAPTER.encodeWithTag(writer, 9, value.radioButton)
        CheckBoxComponent.ADAPTER.encodeWithTag(writer, 8, value.checkbox)
        ToggleComponent.ADAPTER.encodeWithTag(writer, 7, value.toggle)
        SliderComponent.ADAPTER.encodeWithTag(writer, 6, value.slider)
        TextEditorComponent.ADAPTER.encodeWithTag(writer, 5, value.textEditor)
        TextFieldComponent.ADAPTER.encodeWithTag(writer, 4, value.textField)
        ImageComponent.ADAPTER.encodeWithTag(writer, 3, value.image)
        TextComponent.ADAPTER.encodeWithTag(writer, 2, value.label)
        ButtonComponent.ADAPTER.encodeWithTag(writer, 1, value.button)
      }

      public override fun decode(reader: ProtoReader): ElementComponent {
        var button: ButtonComponent? = null
        var label: TextComponent? = null
        var image: ImageComponent? = null
        var textField: TextFieldComponent? = null
        var textEditor: TextEditorComponent? = null
        var slider: SliderComponent? = null
        var toggle: ToggleComponent? = null
        var checkbox: CheckBoxComponent? = null
        var radioButton: RadioButtonComponent? = null
        var picker: PickerComponent? = null
        var topAppBar: TopAppBarComponent? = null
        var bottomBarItem: BottomBarItemComponent? = null
        var alert: AlertComponent? = null
        var actionSheet: ActionSheetComponent? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> button = ButtonComponent.ADAPTER.decode(reader)
            2 -> label = TextComponent.ADAPTER.decode(reader)
            3 -> image = ImageComponent.ADAPTER.decode(reader)
            4 -> textField = TextFieldComponent.ADAPTER.decode(reader)
            5 -> textEditor = TextEditorComponent.ADAPTER.decode(reader)
            6 -> slider = SliderComponent.ADAPTER.decode(reader)
            7 -> toggle = ToggleComponent.ADAPTER.decode(reader)
            8 -> checkbox = CheckBoxComponent.ADAPTER.decode(reader)
            9 -> radioButton = RadioButtonComponent.ADAPTER.decode(reader)
            10 -> picker = PickerComponent.ADAPTER.decode(reader)
            11 -> topAppBar = TopAppBarComponent.ADAPTER.decode(reader)
            12 -> bottomBarItem = BottomBarItemComponent.ADAPTER.decode(reader)
            13 -> alert = AlertComponent.ADAPTER.decode(reader)
            14 -> actionSheet = ActionSheetComponent.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ElementComponent(
          button = button,
          label = label,
          image = image,
          textField = textField,
          textEditor = textEditor,
          slider = slider,
          toggle = toggle,
          checkbox = checkbox,
          radioButton = radioButton,
          picker = picker,
          topAppBar = topAppBar,
          bottomBarItem = bottomBarItem,
          alert = alert,
          actionSheet = actionSheet,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ElementComponent): ElementComponent = value.copy(
        button = value.button?.let(ButtonComponent.ADAPTER::redact),
        label = value.label?.let(TextComponent.ADAPTER::redact),
        image = value.image?.let(ImageComponent.ADAPTER::redact),
        textField = value.textField?.let(TextFieldComponent.ADAPTER::redact),
        textEditor = value.textEditor?.let(TextEditorComponent.ADAPTER::redact),
        slider = value.slider?.let(SliderComponent.ADAPTER::redact),
        toggle = value.toggle?.let(ToggleComponent.ADAPTER::redact),
        checkbox = value.checkbox?.let(CheckBoxComponent.ADAPTER::redact),
        radioButton = value.radioButton?.let(RadioButtonComponent.ADAPTER::redact),
        picker = value.picker?.let(PickerComponent.ADAPTER::redact),
        topAppBar = value.topAppBar?.let(TopAppBarComponent.ADAPTER::redact),
        bottomBarItem = value.bottomBarItem?.let(BottomBarItemComponent.ADAPTER::redact),
        alert = value.alert?.let(AlertComponent.ADAPTER::redact),
        actionSheet = value.actionSheet?.let(ActionSheetComponent.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ElementComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
