// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.FontFamily in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class FontFamily(
  public override val `value`: Int,
) : WireEnum {
  UNDEFINED(0),
  SYSTEM_DEFAULT(1),
  SANS_SERIF(2),
  SERIF(3),
  MONOSPACE(4),
  CUSTOM_FONT(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FontFamily> = object : EnumAdapter<FontFamily>(
      FontFamily::class, 
      PROTO_3, 
      FontFamily.UNDEFINED
    ) {
      public override fun fromValue(`value`: Int): FontFamily? = FontFamily.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): FontFamily? = when (value) {
      0 -> UNDEFINED
      1 -> SYSTEM_DEFAULT
      2 -> SANS_SERIF
      3 -> SERIF
      4 -> MONOSPACE
      5 -> CUSTOM_FONT
      else -> null
    }
  }
}
