// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.IconComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Image Element used to display an icon
 */
public class IconComponent(
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.SymbolToken#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val symbol: SymbolToken = SymbolToken.XXX,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
  )
  public val description: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<IconComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is IconComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (symbol != other.symbol) return false
    if (description != other.description) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + symbol.hashCode()
      result = result * 37 + (description?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """symbol=$symbol"""
    if (description != null) result += """description=${sanitize(description)}"""
    return result.joinToString(prefix = "IconComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    symbol: SymbolToken = this.symbol,
    description: String? = this.description,
    unknownFields: ByteString = this.unknownFields,
  ): IconComponent = IconComponent(symbol, description, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<IconComponent> = object : ProtoAdapter<IconComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      IconComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.IconComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: IconComponent): Int {
        var size = value.unknownFields.size
        if (value.symbol != SymbolToken.XXX) size += SymbolToken.ADAPTER.encodedSizeWithTag(1,
            value.symbol)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.description)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: IconComponent): Unit {
        if (value.symbol != SymbolToken.XXX) SymbolToken.ADAPTER.encodeWithTag(writer, 1,
            value.symbol)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: IconComponent): Unit {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.description)
        if (value.symbol != SymbolToken.XXX) SymbolToken.ADAPTER.encodeWithTag(writer, 1,
            value.symbol)
      }

      public override fun decode(reader: ProtoReader): IconComponent {
        var symbol: SymbolToken = SymbolToken.XXX
        var description: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              symbol = SymbolToken.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> description = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return IconComponent(
          symbol = symbol,
          description = description,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: IconComponent): IconComponent = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<IconComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
