// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.IconComponent in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

/**
 * Element used to display an System Icon
 */
public enum class IconComponent(
  public override val `value`: Int,
) : WireEnum {
  DEFAULT_ACCOUNT_BOX(0),
  DEFAULT_ACCOUNT_CIRCLE(1),
  DEFAULT_ADD_CIRCLE(2),
  DEFAULT_ADD(3),
  DEFAULT_ARROW_BACK(4),
  DEFAULT_ARROW_DROP_DOWN(5),
  DEFAULT_ARROW_FORWARD(6),
  DEFAULT_BUILD(7),
  DEFAULT_CALL(8),
  DEFAULT_CHECK_CIRCLE(9),
  DEFAULT_CHECK(10),
  DEFAULT_CLEAR(11),
  DEFAULT_CLOSE(12),
  DEFAULT_CREATE(13),
  DEFAULT_DATE_RANGE(14),
  DEFAULT_DELETE(15),
  DEFAULT_DONE(16),
  DEFAULT_EDIT(17),
  DEFAULT_EMAIL(18),
  DEFAULT_EXIT_TO_APP(19),
  DEFAULT_FACE(20),
  DEFAULT_FAVORITE_BORDER(21),
  DEFAULT_FAVORITE(22),
  DEFAULT_HOME(23),
  DEFAULT_INFO(24),
  DEFAULT_KEYBOARD_ARROW_DOWN(25),
  DEFAULT_KEYBOARD_ARROW_LEFT(26),
  DEFAULT_KEYBOARD_ARROW_RIGHT(27),
  DEFAULT_KEYBOARD_ARROW_UP(28),
  DEFAULT_LIST(29),
  DEFAULT_LOCATION_ON(30),
  DEFAULT_LOCK(31),
  DEFAULT_MAIL_OUTLINE(32),
  DEFAULT_MENU(33),
  DEFAULT_MOR_EVERT(34),
  DEFAULT_NOTIFICATIONS(35),
  DEFAULT_PERSON(36),
  DEFAULT_PHONE(37),
  DEFAULT_PLACE(38),
  DEFAULT_PLAY_ARROW(39),
  DEFAULT_REFRESH(40),
  DEFAULT_SEARCH(41),
  DEFAULT_SEND(42),
  DEFAULT_SETTINGS(43),
  DEFAULT_SHARE(44),
  DEFAULT_SHOPPINGCART(45),
  DEFAULT_STAR(46),
  DEFAULT_THUMBUP(47),
  DEFAULT_WARNING(48),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<IconComponent> = object : EnumAdapter<IconComponent>(
      IconComponent::class, 
      PROTO_3, 
      IconComponent.DEFAULT_ACCOUNT_BOX
    ) {
      public override fun fromValue(`value`: Int): IconComponent? = IconComponent.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): IconComponent? = when (value) {
      0 -> DEFAULT_ACCOUNT_BOX
      1 -> DEFAULT_ACCOUNT_CIRCLE
      2 -> DEFAULT_ADD_CIRCLE
      3 -> DEFAULT_ADD
      4 -> DEFAULT_ARROW_BACK
      5 -> DEFAULT_ARROW_DROP_DOWN
      6 -> DEFAULT_ARROW_FORWARD
      7 -> DEFAULT_BUILD
      8 -> DEFAULT_CALL
      9 -> DEFAULT_CHECK_CIRCLE
      10 -> DEFAULT_CHECK
      11 -> DEFAULT_CLEAR
      12 -> DEFAULT_CLOSE
      13 -> DEFAULT_CREATE
      14 -> DEFAULT_DATE_RANGE
      15 -> DEFAULT_DELETE
      16 -> DEFAULT_DONE
      17 -> DEFAULT_EDIT
      18 -> DEFAULT_EMAIL
      19 -> DEFAULT_EXIT_TO_APP
      20 -> DEFAULT_FACE
      21 -> DEFAULT_FAVORITE_BORDER
      22 -> DEFAULT_FAVORITE
      23 -> DEFAULT_HOME
      24 -> DEFAULT_INFO
      25 -> DEFAULT_KEYBOARD_ARROW_DOWN
      26 -> DEFAULT_KEYBOARD_ARROW_LEFT
      27 -> DEFAULT_KEYBOARD_ARROW_RIGHT
      28 -> DEFAULT_KEYBOARD_ARROW_UP
      29 -> DEFAULT_LIST
      30 -> DEFAULT_LOCATION_ON
      31 -> DEFAULT_LOCK
      32 -> DEFAULT_MAIL_OUTLINE
      33 -> DEFAULT_MENU
      34 -> DEFAULT_MOR_EVERT
      35 -> DEFAULT_NOTIFICATIONS
      36 -> DEFAULT_PERSON
      37 -> DEFAULT_PHONE
      38 -> DEFAULT_PLACE
      39 -> DEFAULT_PLAY_ARROW
      40 -> DEFAULT_REFRESH
      41 -> DEFAULT_SEARCH
      42 -> DEFAULT_SEND
      43 -> DEFAULT_SETTINGS
      44 -> DEFAULT_SHARE
      45 -> DEFAULT_SHOPPINGCART
      46 -> DEFAULT_STAR
      47 -> DEFAULT_THUMBUP
      48 -> DEFAULT_WARNING
      else -> null
    }
  }
}
