// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.LazyColumnComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Lazy column layout component.
 */
public class LazyColumnComponent(
  elements: List<Particle> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.Arrangement#ADAPTER",
  )
  public val arrangement: Arrangement? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.yunlong.particle.proto.Alignment#ADAPTER",
  )
  public val alignment: Alignment? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.yunlong.particle.proto.SizeModifier#ADAPTER",
  )
  public val spacing: SizeModifier? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
  )
  public val reverseLayout: Boolean? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.yunlong.particle.proto.InsetsModifier#ADAPTER",
  )
  public val contentPadding: InsetsModifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<LazyColumnComponent, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val elements: List<Particle> = immutableCopyOf("elements", elements)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LazyColumnComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (elements != other.elements) return false
    if (arrangement != other.arrangement) return false
    if (alignment != other.alignment) return false
    if (spacing != other.spacing) return false
    if (reverseLayout != other.reverseLayout) return false
    if (contentPadding != other.contentPadding) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + elements.hashCode()
      result = result * 37 + (arrangement?.hashCode() ?: 0)
      result = result * 37 + (alignment?.hashCode() ?: 0)
      result = result * 37 + (spacing?.hashCode() ?: 0)
      result = result * 37 + (reverseLayout?.hashCode() ?: 0)
      result = result * 37 + (contentPadding?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (elements.isNotEmpty()) result += """elements=$elements"""
    if (arrangement != null) result += """arrangement=$arrangement"""
    if (alignment != null) result += """alignment=$alignment"""
    if (spacing != null) result += """spacing=$spacing"""
    if (reverseLayout != null) result += """reverseLayout=$reverseLayout"""
    if (contentPadding != null) result += """contentPadding=$contentPadding"""
    return result.joinToString(prefix = "LazyColumnComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    elements: List<Particle> = this.elements,
    arrangement: Arrangement? = this.arrangement,
    alignment: Alignment? = this.alignment,
    spacing: SizeModifier? = this.spacing,
    reverseLayout: Boolean? = this.reverseLayout,
    contentPadding: InsetsModifier? = this.contentPadding,
    unknownFields: ByteString = this.unknownFields,
  ): LazyColumnComponent = LazyColumnComponent(elements, arrangement, alignment, spacing,
      reverseLayout, contentPadding, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LazyColumnComponent> = object :
        ProtoAdapter<LazyColumnComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      LazyColumnComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.LazyColumnComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: LazyColumnComponent): Int {
        var size = value.unknownFields.size
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.elements)
        size += Arrangement.ADAPTER.encodedSizeWithTag(2, value.arrangement)
        size += Alignment.ADAPTER.encodedSizeWithTag(3, value.alignment)
        size += SizeModifier.ADAPTER.encodedSizeWithTag(4, value.spacing)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.reverseLayout)
        size += InsetsModifier.ADAPTER.encodedSizeWithTag(6, value.contentPadding)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: LazyColumnComponent): Unit {
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
        Arrangement.ADAPTER.encodeWithTag(writer, 2, value.arrangement)
        Alignment.ADAPTER.encodeWithTag(writer, 3, value.alignment)
        SizeModifier.ADAPTER.encodeWithTag(writer, 4, value.spacing)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.reverseLayout)
        InsetsModifier.ADAPTER.encodeWithTag(writer, 6, value.contentPadding)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: LazyColumnComponent): Unit {
        writer.writeBytes(value.unknownFields)
        InsetsModifier.ADAPTER.encodeWithTag(writer, 6, value.contentPadding)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.reverseLayout)
        SizeModifier.ADAPTER.encodeWithTag(writer, 4, value.spacing)
        Alignment.ADAPTER.encodeWithTag(writer, 3, value.alignment)
        Arrangement.ADAPTER.encodeWithTag(writer, 2, value.arrangement)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
      }

      public override fun decode(reader: ProtoReader): LazyColumnComponent {
        val elements = mutableListOf<Particle>()
        var arrangement: Arrangement? = null
        var alignment: Alignment? = null
        var spacing: SizeModifier? = null
        var reverseLayout: Boolean? = null
        var contentPadding: InsetsModifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> elements.add(Particle.ADAPTER.decode(reader))
            2 -> try {
              arrangement = Arrangement.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> try {
              alignment = Alignment.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> spacing = SizeModifier.ADAPTER.decode(reader)
            5 -> reverseLayout = ProtoAdapter.BOOL.decode(reader)
            6 -> contentPadding = InsetsModifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LazyColumnComponent(
          elements = elements,
          arrangement = arrangement,
          alignment = alignment,
          spacing = spacing,
          reverseLayout = reverseLayout,
          contentPadding = contentPadding,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: LazyColumnComponent): LazyColumnComponent = value.copy(
        elements = value.elements.redactElements(Particle.ADAPTER),
        spacing = value.spacing?.let(SizeModifier.ADAPTER::redact),
        contentPadding = value.contentPadding?.let(InsetsModifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<LazyColumnComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
