// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ModalDrawerComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ModalDrawerComponent(
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val content: Particle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ModalDrawerComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ModalDrawerComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (content != other.content) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (content?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (content != null) result += """content=$content"""
    return result.joinToString(prefix = "ModalDrawerComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(content: Particle? = this.content, unknownFields: ByteString =
      this.unknownFields): ModalDrawerComponent = ModalDrawerComponent(content, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ModalDrawerComponent> = object :
        ProtoAdapter<ModalDrawerComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ModalDrawerComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ModalDrawerComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ModalDrawerComponent): Int {
        var size = value.unknownFields.size
        if (value.content != null) size += Particle.ADAPTER.encodedSizeWithTag(1, value.content)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ModalDrawerComponent): Unit {
        if (value.content != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.content)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ModalDrawerComponent): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.content != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.content)
      }

      public override fun decode(reader: ProtoReader): ModalDrawerComponent {
        var content: Particle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> content = Particle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ModalDrawerComponent(
          content = content,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ModalDrawerComponent): ModalDrawerComponent = value.copy(
        content = value.content?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ModalDrawerComponent> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
