// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.NavigationViewComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Navigation view layout component.
 */
public class NavigationViewComponent(
  elements: List<Particle> = emptyList(),
  bars: List<Particle> = emptyList(),
  /**
   * The currently selected item id in the NavigationView
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "selectedElement",
  )
  public val selected_element: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<NavigationViewComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Child elements in the component.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val elements: List<Particle> = immutableCopyOf("elements", elements)

  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val bars: List<Particle> = immutableCopyOf("bars", bars)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NavigationViewComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (elements != other.elements) return false
    if (bars != other.bars) return false
    if (selected_element != other.selected_element) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + elements.hashCode()
      result = result * 37 + bars.hashCode()
      result = result * 37 + selected_element.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (elements.isNotEmpty()) result += """elements=$elements"""
    if (bars.isNotEmpty()) result += """bars=$bars"""
    result += """selected_element=${sanitize(selected_element)}"""
    return result.joinToString(prefix = "NavigationViewComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    elements: List<Particle> = this.elements,
    bars: List<Particle> = this.bars,
    selected_element: String = this.selected_element,
    unknownFields: ByteString = this.unknownFields,
  ): NavigationViewComponent = NavigationViewComponent(elements, bars, selected_element,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NavigationViewComponent> = object :
        ProtoAdapter<NavigationViewComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      NavigationViewComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.NavigationViewComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: NavigationViewComponent): Int {
        var size = value.unknownFields.size
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.elements)
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(2, value.bars)
        if (value.selected_element != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3,
            value.selected_element)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: NavigationViewComponent): Unit {
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.bars)
        if (value.selected_element != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.selected_element)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: NavigationViewComponent):
          Unit {
        writer.writeBytes(value.unknownFields)
        if (value.selected_element != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.selected_element)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.bars)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.elements)
      }

      public override fun decode(reader: ProtoReader): NavigationViewComponent {
        val elements = mutableListOf<Particle>()
        val bars = mutableListOf<Particle>()
        var selected_element: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> elements.add(Particle.ADAPTER.decode(reader))
            2 -> bars.add(Particle.ADAPTER.decode(reader))
            3 -> selected_element = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NavigationViewComponent(
          elements = elements,
          bars = bars,
          selected_element = selected_element,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: NavigationViewComponent): NavigationViewComponent =
          value.copy(
        elements = value.elements.redactElements(Particle.ADAPTER),
        bars = value.bars.redactElements(Particle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<NavigationViewComponent> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
