// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.NavigateToAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Action to open a new screen
 */
public class NavigateToAction(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val target: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.NavigationMode#ADAPTER",
  )
  public val mode: NavigationMode? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<NavigateToAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NavigateToAction) return false
    if (unknownFields != other.unknownFields) return false
    if (target != other.target) return false
    if (mode != other.mode) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + target.hashCode()
      result = result * 37 + (mode?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """target=${sanitize(target)}"""
    if (mode != null) result += """mode=$mode"""
    return result.joinToString(prefix = "NavigateToAction{", separator = ", ", postfix = "}")
  }

  public fun copy(
    target: String = this.target,
    mode: NavigationMode? = this.mode,
    unknownFields: ByteString = this.unknownFields,
  ): NavigateToAction = NavigateToAction(target, mode, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NavigateToAction> = object : ProtoAdapter<NavigateToAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      NavigateToAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.NavigateToAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: NavigateToAction): Int {
        var size = value.unknownFields.size
        if (value.target != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.target)
        size += NavigationMode.ADAPTER.encodedSizeWithTag(2, value.mode)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: NavigateToAction): Unit {
        if (value.target != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.target)
        NavigationMode.ADAPTER.encodeWithTag(writer, 2, value.mode)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: NavigateToAction): Unit {
        writer.writeBytes(value.unknownFields)
        NavigationMode.ADAPTER.encodeWithTag(writer, 2, value.mode)
        if (value.target != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.target)
      }

      public override fun decode(reader: ProtoReader): NavigateToAction {
        var target: String = ""
        var mode: NavigationMode? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> target = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              mode = NavigationMode.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return NavigateToAction(
          target = target,
          mode = mode,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: NavigateToAction): NavigateToAction = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<NavigateToAction> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
