// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.NavigationBarItemComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * NavigationViewItem Element used to create an item for a navigation view.
 */
public class NavigationBarItemComponent(
  /**
   * Text to display for the item.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val text: Particle? = null,
  /**
   * Icon to display for the item.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val icon: Particle? = null,
  /**
   * Whether this item is selected.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val selected: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<NavigationBarItemComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NavigationBarItemComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    if (icon != other.icon) return false
    if (selected != other.selected) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (icon?.hashCode() ?: 0)
      result = result * 37 + selected.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (text != null) result += """text=$text"""
    if (icon != null) result += """icon=$icon"""
    result += """selected=$selected"""
    return result.joinToString(prefix = "NavigationBarItemComponent{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    text: Particle? = this.text,
    icon: Particle? = this.icon,
    selected: Boolean = this.selected,
    unknownFields: ByteString = this.unknownFields,
  ): NavigationBarItemComponent = NavigationBarItemComponent(text, icon, selected, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NavigationBarItemComponent> = object :
        ProtoAdapter<NavigationBarItemComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      NavigationBarItemComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.NavigationBarItemComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: NavigationBarItemComponent): Int {
        var size = value.unknownFields.size
        if (value.text != null) size += Particle.ADAPTER.encodedSizeWithTag(1, value.text)
        if (value.icon != null) size += Particle.ADAPTER.encodedSizeWithTag(2, value.icon)
        if (value.selected != false) size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.selected)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: NavigationBarItemComponent): Unit {
        if (value.text != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.text)
        if (value.icon != null) Particle.ADAPTER.encodeWithTag(writer, 2, value.icon)
        if (value.selected != false) ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.selected)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: NavigationBarItemComponent):
          Unit {
        writer.writeBytes(value.unknownFields)
        if (value.selected != false) ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.selected)
        if (value.icon != null) Particle.ADAPTER.encodeWithTag(writer, 2, value.icon)
        if (value.text != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.text)
      }

      public override fun decode(reader: ProtoReader): NavigationBarItemComponent {
        var text: Particle? = null
        var icon: Particle? = null
        var selected: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = Particle.ADAPTER.decode(reader)
            2 -> icon = Particle.ADAPTER.decode(reader)
            3 -> selected = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NavigationBarItemComponent(
          text = text,
          icon = icon,
          selected = selected,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: NavigationBarItemComponent): NavigationBarItemComponent =
          value.copy(
        text = value.text?.let(Particle.ADAPTER::redact),
        icon = value.icon?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<NavigationBarItemComponent> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
