// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.OffsetModifier in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class OffsetModifier(
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.SizeModifier#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val xOffset: SizeModifier? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.SizeModifier#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val yOffset: SizeModifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<OffsetModifier, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is OffsetModifier) return false
    if (unknownFields != other.unknownFields) return false
    if (xOffset != other.xOffset) return false
    if (yOffset != other.yOffset) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (xOffset?.hashCode() ?: 0)
      result = result * 37 + (yOffset?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (xOffset != null) result += """xOffset=$xOffset"""
    if (yOffset != null) result += """yOffset=$yOffset"""
    return result.joinToString(prefix = "OffsetModifier{", separator = ", ", postfix = "}")
  }

  public fun copy(
    xOffset: SizeModifier? = this.xOffset,
    yOffset: SizeModifier? = this.yOffset,
    unknownFields: ByteString = this.unknownFields,
  ): OffsetModifier = OffsetModifier(xOffset, yOffset, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<OffsetModifier> = object : ProtoAdapter<OffsetModifier>(
      FieldEncoding.LENGTH_DELIMITED, 
      OffsetModifier::class, 
      "type.googleapis.com/com.yunlong.particle.proto.OffsetModifier", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: OffsetModifier): Int {
        var size = value.unknownFields.size
        if (value.xOffset != null) size += SizeModifier.ADAPTER.encodedSizeWithTag(1, value.xOffset)
        if (value.yOffset != null) size += SizeModifier.ADAPTER.encodedSizeWithTag(2, value.yOffset)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: OffsetModifier): Unit {
        if (value.xOffset != null) SizeModifier.ADAPTER.encodeWithTag(writer, 1, value.xOffset)
        if (value.yOffset != null) SizeModifier.ADAPTER.encodeWithTag(writer, 2, value.yOffset)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: OffsetModifier): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.yOffset != null) SizeModifier.ADAPTER.encodeWithTag(writer, 2, value.yOffset)
        if (value.xOffset != null) SizeModifier.ADAPTER.encodeWithTag(writer, 1, value.xOffset)
      }

      public override fun decode(reader: ProtoReader): OffsetModifier {
        var xOffset: SizeModifier? = null
        var yOffset: SizeModifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> xOffset = SizeModifier.ADAPTER.decode(reader)
            2 -> yOffset = SizeModifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return OffsetModifier(
          xOffset = xOffset,
          yOffset = yOffset,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: OffsetModifier): OffsetModifier = value.copy(
        xOffset = value.xOffset?.let(SizeModifier.ADAPTER::redact),
        yOffset = value.yOffset?.let(SizeModifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<OffsetModifier> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
