// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.OpenExternalAppAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Action to open the browser, mailbox, phone, camera, etc.
 */
public class OpenExternalAppAction(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val url: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<OpenExternalAppAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is OpenExternalAppAction) return false
    if (unknownFields != other.unknownFields) return false
    if (url != other.url) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + url.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """url=${sanitize(url)}"""
    return result.joinToString(prefix = "OpenExternalAppAction{", separator = ", ", postfix = "}")
  }

  public fun copy(url: String = this.url, unknownFields: ByteString = this.unknownFields):
      OpenExternalAppAction = OpenExternalAppAction(url, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<OpenExternalAppAction> = object :
        ProtoAdapter<OpenExternalAppAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      OpenExternalAppAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.OpenExternalAppAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: OpenExternalAppAction): Int {
        var size = value.unknownFields.size
        if (value.url != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: OpenExternalAppAction): Unit {
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: OpenExternalAppAction): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
      }

      public override fun decode(reader: ProtoReader): OpenExternalAppAction {
        var url: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> url = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return OpenExternalAppAction(
          url = url,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: OpenExternalAppAction): OpenExternalAppAction =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<OpenExternalAppAction> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
