// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.PhoneType in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class PhoneType(
  public override val `value`: Int,
) : WireEnum {
  MOBILE(0),
  HOME(1),
  WORK(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PhoneType> = object : EnumAdapter<PhoneType>(
      PhoneType::class, 
      PROTO_3, 
      PhoneType.MOBILE
    ) {
      public override fun fromValue(`value`: Int): PhoneType? = PhoneType.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): PhoneType? = when (value) {
      0 -> MOBILE
      1 -> HOME
      2 -> WORK
      else -> null
    }
  }
}
