// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.PickerComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Picker layout used to create a dropdown list
 */
public class PickerComponent(
  options: List<Particle> = emptyList(),
  /**
   * The currently selected item ID in the dropdown
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "selectedOption",
  )
  public val selected_option: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<PickerComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * The list of options available in the dropdown
   */
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val options: List<Particle> = immutableCopyOf("options", options)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PickerComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (options != other.options) return false
    if (selected_option != other.selected_option) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + options.hashCode()
      result = result * 37 + selected_option.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (options.isNotEmpty()) result += """options=$options"""
    result += """selected_option=${sanitize(selected_option)}"""
    return result.joinToString(prefix = "PickerComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    options: List<Particle> = this.options,
    selected_option: String = this.selected_option,
    unknownFields: ByteString = this.unknownFields,
  ): PickerComponent = PickerComponent(options, selected_option, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PickerComponent> = object : ProtoAdapter<PickerComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      PickerComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.PickerComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: PickerComponent): Int {
        var size = value.unknownFields.size
        size += Particle.ADAPTER.asRepeated().encodedSizeWithTag(1, value.options)
        if (value.selected_option != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.selected_option)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: PickerComponent): Unit {
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.options)
        if (value.selected_option != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.selected_option)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: PickerComponent): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.selected_option != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.selected_option)
        Particle.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.options)
      }

      public override fun decode(reader: ProtoReader): PickerComponent {
        val options = mutableListOf<Particle>()
        var selected_option: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> options.add(Particle.ADAPTER.decode(reader))
            2 -> selected_option = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PickerComponent(
          options = options,
          selected_option = selected_option,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: PickerComponent): PickerComponent = value.copy(
        options = value.options.redactElements(Particle.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<PickerComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
