// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.RequestType in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class RequestType(
  public override val `value`: Int,
) : WireEnum {
  GET(0),
  POST(1),
  PUT(2),
  DELETE(3),
  HEAD(4),
  OPTIONS(5),
  CONNECT(6),
  TRACE(7),
  PATCH(8),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RequestType> = object : EnumAdapter<RequestType>(
      RequestType::class, 
      PROTO_3, 
      RequestType.GET
    ) {
      public override fun fromValue(`value`: Int): RequestType? = RequestType.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): RequestType? = when (value) {
      0 -> GET
      1 -> POST
      2 -> PUT
      3 -> DELETE
      4 -> HEAD
      5 -> OPTIONS
      6 -> CONNECT
      7 -> TRACE
      8 -> PATCH
      else -> null
    }
  }
}
