// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.RetrieveDataAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Action to retrieve data
 */
public class RetrieveDataAction(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val key: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
  )
  public val value_: String = "",
  subsequentAction: List<Action> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<RetrieveDataAction, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    adapter = "com.yunlong.particle.proto.Action#ADAPTER",
    label = WireField.Label.REPEATED,
  )
  public val subsequentAction: List<Action> = immutableCopyOf("subsequentAction", subsequentAction)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RetrieveDataAction) return false
    if (unknownFields != other.unknownFields) return false
    if (key != other.key) return false
    if (value_ != other.value_) return false
    if (subsequentAction != other.subsequentAction) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + key.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + subsequentAction.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """key=${sanitize(key)}"""
    result += """value_=${sanitize(value_)}"""
    if (subsequentAction.isNotEmpty()) result += """subsequentAction=$subsequentAction"""
    return result.joinToString(prefix = "RetrieveDataAction{", separator = ", ", postfix = "}")
  }

  public fun copy(
    key: String = this.key,
    value_: String = this.value_,
    subsequentAction: List<Action> = this.subsequentAction,
    unknownFields: ByteString = this.unknownFields,
  ): RetrieveDataAction = RetrieveDataAction(key, value_, subsequentAction, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RetrieveDataAction> = object :
        ProtoAdapter<RetrieveDataAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      RetrieveDataAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.RetrieveDataAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: RetrieveDataAction): Int {
        var size = value.unknownFields.size
        if (value.key != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.key)
        if (value.value_ != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.value_)
        size += Action.ADAPTER.asRepeated().encodedSizeWithTag(3, value.subsequentAction)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: RetrieveDataAction): Unit {
        if (value.key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
        if (value.value_ != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.subsequentAction)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: RetrieveDataAction): Unit {
        writer.writeBytes(value.unknownFields)
        Action.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.subsequentAction)
        if (value.value_ != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        if (value.key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
      }

      public override fun decode(reader: ProtoReader): RetrieveDataAction {
        var key: String = ""
        var value_: String = ""
        val subsequentAction = mutableListOf<Action>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> key = ProtoAdapter.STRING.decode(reader)
            2 -> value_ = ProtoAdapter.STRING.decode(reader)
            3 -> subsequentAction.add(Action.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RetrieveDataAction(
          key = key,
          value_ = value_,
          subsequentAction = subsequentAction,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: RetrieveDataAction): RetrieveDataAction = value.copy(
        subsequentAction = value.subsequentAction.redactElements(Action.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<RetrieveDataAction> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
