// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ShadowModifier in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class ShadowModifier(
  public override val `value`: Int,
) : WireEnum {
  DEFAULT(0),
  SHADOW_1(1),
  SHADOW_2(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ShadowModifier> = object : EnumAdapter<ShadowModifier>(
      ShadowModifier::class, 
      PROTO_3, 
      ShadowModifier.DEFAULT
    ) {
      public override fun fromValue(`value`: Int): ShadowModifier? = ShadowModifier.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ShadowModifier? = when (value) {
      0 -> DEFAULT
      1 -> SHADOW_1
      2 -> SHADOW_2
      else -> null
    }
  }
}
