// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ShowDialogAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Action to show a dialog
 */
public class ShowDialogAction(
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val dialog: Particle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ShowDialogAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ShowDialogAction) return false
    if (unknownFields != other.unknownFields) return false
    if (dialog != other.dialog) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (dialog?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (dialog != null) result += """dialog=$dialog"""
    return result.joinToString(prefix = "ShowDialogAction{", separator = ", ", postfix = "}")
  }

  public fun copy(dialog: Particle? = this.dialog, unknownFields: ByteString = this.unknownFields):
      ShowDialogAction = ShowDialogAction(dialog, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ShowDialogAction> = object : ProtoAdapter<ShowDialogAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      ShowDialogAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ShowDialogAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ShowDialogAction): Int {
        var size = value.unknownFields.size
        if (value.dialog != null) size += Particle.ADAPTER.encodedSizeWithTag(1, value.dialog)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ShowDialogAction): Unit {
        if (value.dialog != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.dialog)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ShowDialogAction): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.dialog != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.dialog)
      }

      public override fun decode(reader: ProtoReader): ShowDialogAction {
        var dialog: Particle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> dialog = Particle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ShowDialogAction(
          dialog = dialog,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ShowDialogAction): ShowDialogAction = value.copy(
        dialog = value.dialog?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ShowDialogAction> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
