// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.ShowMenuAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * / Action to show a menu
 */
public class ShowMenuAction(
  @field:WireField(
    tag = 1,
    adapter = "com.yunlong.particle.proto.Particle#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val menu: Particle? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ShowMenuAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ShowMenuAction) return false
    if (unknownFields != other.unknownFields) return false
    if (menu != other.menu) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (menu?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (menu != null) result += """menu=$menu"""
    return result.joinToString(prefix = "ShowMenuAction{", separator = ", ", postfix = "}")
  }

  public fun copy(menu: Particle? = this.menu, unknownFields: ByteString = this.unknownFields):
      ShowMenuAction = ShowMenuAction(menu, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ShowMenuAction> = object : ProtoAdapter<ShowMenuAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      ShowMenuAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.ShowMenuAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: ShowMenuAction): Int {
        var size = value.unknownFields.size
        if (value.menu != null) size += Particle.ADAPTER.encodedSizeWithTag(1, value.menu)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ShowMenuAction): Unit {
        if (value.menu != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.menu)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ShowMenuAction): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.menu != null) Particle.ADAPTER.encodeWithTag(writer, 1, value.menu)
      }

      public override fun decode(reader: ProtoReader): ShowMenuAction {
        var menu: Particle? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> menu = Particle.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ShowMenuAction(
          menu = menu,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ShowMenuAction): ShowMenuAction = value.copy(
        menu = value.menu?.let(Particle.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ShowMenuAction> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
