// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.SizeToken in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class SizeToken(
  public override val `value`: Int,
) : WireEnum {
  SIZE_TOKEN_0(0),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SizeToken> = object : EnumAdapter<SizeToken>(
      SizeToken::class, 
      PROTO_3, 
      SizeToken.SIZE_TOKEN_0
    ) {
      public override fun fromValue(`value`: Int): SizeToken? = SizeToken.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): SizeToken? = when (value) {
      0 -> SIZE_TOKEN_0
      else -> null
    }
  }
}
