// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.SymbolToken in generate/particle.proto
package com.yunlong.particle.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class SymbolToken(
  public override val `value`: Int,
) : WireEnum {
  XXX(0),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SymbolToken> = object : EnumAdapter<SymbolToken>(
      SymbolToken::class, 
      PROTO_3, 
      SymbolToken.XXX
    ) {
      public override fun fromValue(`value`: Int): SymbolToken? = SymbolToken.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): SymbolToken? = when (value) {
      0 -> XXX
      else -> null
    }
  }
}
