// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.TextFieldComponent in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * TextField Element used to create a text field
 */
public class TextFieldComponent(
  /**
   * Optional placeholder text to display when the field is empty
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
  )
  public val placeholder: String? = null,
  /**
   * The initial value of the text field
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    declaredName = "value",
  )
  public val value_: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<TextFieldComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TextFieldComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (placeholder != other.placeholder) return false
    if (value_ != other.value_) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (placeholder?.hashCode() ?: 0)
      result = result * 37 + (value_?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (placeholder != null) result += """placeholder=${sanitize(placeholder)}"""
    if (value_ != null) result += """value_=${sanitize(value_)}"""
    return result.joinToString(prefix = "TextFieldComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    placeholder: String? = this.placeholder,
    value_: String? = this.value_,
    unknownFields: ByteString = this.unknownFields,
  ): TextFieldComponent = TextFieldComponent(placeholder, value_, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextFieldComponent> = object :
        ProtoAdapter<TextFieldComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      TextFieldComponent::class, 
      "type.googleapis.com/com.yunlong.particle.proto.TextFieldComponent", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: TextFieldComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.placeholder)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.value_)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: TextFieldComponent): Unit {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.placeholder)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: TextFieldComponent): Unit {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value_)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.placeholder)
      }

      public override fun decode(reader: ProtoReader): TextFieldComponent {
        var placeholder: String? = null
        var value_: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> placeholder = ProtoAdapter.STRING.decode(reader)
            2 -> value_ = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TextFieldComponent(
          placeholder = placeholder,
          value_ = value_,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: TextFieldComponent): TextFieldComponent = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<TextFieldComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
