// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.yunlong.particle.proto.UpdateModifierAction in generate/particle.proto
package com.yunlong.particle.proto

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Action to update the UI modifier
 */
public class UpdateModifierAction(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "override",
  )
  public val override_: Boolean = false,
  @field:WireField(
    tag = 2,
    adapter = "com.yunlong.particle.proto.Modifier#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<UpdateModifierAction, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UpdateModifierAction) return false
    if (unknownFields != other.unknownFields) return false
    if (override_ != other.override_) return false
    if (modifier != other.modifier) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + override_.hashCode()
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """override_=$override_"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "UpdateModifierAction{", separator = ", ", postfix = "}")
  }

  public fun copy(
    override_: Boolean = this.override_,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): UpdateModifierAction = UpdateModifierAction(override_, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UpdateModifierAction> = object :
        ProtoAdapter<UpdateModifierAction>(
      FieldEncoding.LENGTH_DELIMITED, 
      UpdateModifierAction::class, 
      "type.googleapis.com/com.yunlong.particle.proto.UpdateModifierAction", 
      PROTO_3, 
      null, 
      "generate/particle.proto"
    ) {
      public override fun encodedSize(`value`: UpdateModifierAction): Int {
        var size = value.unknownFields.size
        if (value.override_ != false) size += ProtoAdapter.BOOL.encodedSizeWithTag(1,
            value.override_)
        if (value.modifier != null) size += Modifier.ADAPTER.encodedSizeWithTag(2, value.modifier)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: UpdateModifierAction): Unit {
        if (value.override_ != false) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.override_)
        if (value.modifier != null) Modifier.ADAPTER.encodeWithTag(writer, 2, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: UpdateModifierAction): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.modifier != null) Modifier.ADAPTER.encodeWithTag(writer, 2, value.modifier)
        if (value.override_ != false) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.override_)
      }

      public override fun decode(reader: ProtoReader): UpdateModifierAction {
        var override_: Boolean = false
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> override_ = ProtoAdapter.BOOL.decode(reader)
            2 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UpdateModifierAction(
          override_ = override_,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: UpdateModifierAction): UpdateModifierAction = value.copy(
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<UpdateModifierAction> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
